apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxicab-app
  labels:
    app: taxicab-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taxicab-app
  template:
    metadata:
      labels:
        app: taxicab-app
    spec:
      containers:
      - name:  TaxicabApplication
        image: prasannareddychirra/taxi-cab-application:replaceImageTag
        ports:
        - containerPort: 8080